### ISSUE TITLE
Motivo de não estar batendo 100% de coverage

### ISSUE THREAD

**Issue by ErickWendel** [DeeSouza/Challenge-Tests-01#1]
Aqui você usou async e o done, em geral se usa ou um ou o outro. Então pode matar o done

https://github.com/DeeSouza/Challenge-Tests-01/blob/b9e22931ebb1412132c09f9643809dc610631e83/tests/e2e/api.test.js#L14

Aqui faltou só validar o body para bater 100%
https://github.com/DeeSouza/Challenge-Tests-01/blob/b9e22931ebb1412132c09f9643809dc610631e83/tests/e2e/api.test.js#L18

A resolução fica: 

```js
const assert = require('assert')
describe("Route endpoint /team", () => {
    it("should request return HTTP status code 200", async () => {
      await request(app)
        .get("/team")
        .expect("Content-Type", /json/)
        .expect(res => {
          assert.ok(res.body.length > 0)
        })
        .expect(200);
    });
  });
  ```
  
Agora só vai restar um teste para bater os 100%, falta criar um teste para esse IF

https://github.com/DeeSouza/Challenge-Tests-01/blob/b9e22931ebb1412132c09f9643809dc610631e83/src/services/getListPokemonService.js#L37

De resto, ficou excelente! Parabéns pelo esforço!!

**Comment by deesouza-invillia** [comment]
Muito obrigado, entendi o que faltava.

**Comment by DeeSouza** [comment]
Obrigado!
